name: Build and Release Flutter App

on:
  push:
    tags:
      - 'v*' # Se activa cuando se crea un tag como v1.0, v1.2.1, etc.

jobs:
  build-and-release:
    # Otorga permisos para que la acción pueda crear una release en GitHub
    permissions:
      contents: write

    # ¡MUY IMPORTANTE! Especifica que el trabajo debe correr en un entorno de Windows
    runs-on: windows-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Habilitar soporte para escritorio de Windows
        run: flutter config --enable-windows-desktop

      - name: Compilar ejecutable de Windows
        run: flutter build windows --release

      # Este paso crea la release en GitHub y adjunta el ejecutable
      - name: Crear GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          # Busca el ejecutable en la carpeta de compilación de Windows
          files: build/windows/runner/Release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
